---
title: "Sappey 2040"
---

# Nos valeurs

Le collectif Sappey 2040 travaille à construire avec les habitantes et les habitants du village un projet pour faire ensemble du Sappey en Chartreuse un village écologique et solidaire. 

# Notre objectif

Construire ensemble un programme pour les élections municipales 2026.

Nous sommes un groupe de personnes du Sappey réunies autour de l'envie d'échanger et de proposer des idés pour l'avenir de notre village. Notre démarche se veut positive, ouverte et joyeuse !

# Qui sommes nous

Nous sommes un groupe de citoyennes et citoyens réunies autour de l'envie d'échanger et de proposer des idés pour l'avenir de notre village. Notre démarche se veut positive, ouverte et joyeuse !

Nous avons constitué un groupe actif d'habitantes et habitants du Sappey, qui se sont initialements rencontrés lors de la campagne des élections municipales de 2020 et qui ont été rejoins par de nouvelles énergies. N'hésitez pas à nous rejoindre.

Composition du groupe actif 26/06/2025 : *Odile Bertrand, Gildas Bouffaud, Catherine Briot, Pascale Chaumet, Florian de Chezelles, Solène Compingt, Marion Debuisson, Alexis, Nicolas Fertin, Marie-Noelle Gagnepain, Monique Guillet, Philippe Jarry, Guillaume Mirabel, Jean-Louis Mugnier, Alain Pajon, Jean-Marc Plicque, Magali Richard, Laurent Ristord, Yves Urbain*

# Actualités

## Réunion publique du 3 juin 2025